import ENV_VARS from "../../tools/ENV_VARS.js";

export default {
  FETCH_URL: ENV_VARS.SERVER_URL + "/search",
  FETCH_INIT: 'FETCH_INIT',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  NEXT_PAGE_SUCCESS: 'NEXT_PAGE_SUCCESS',
  FETCH_ERROR: 'FETCH_ERROR',
  SPLIT_OFFSET: 10,
  MIN_LINES: 6
}